"""~store

Revision ID: eb2809714bd8
Revises: e9ab0f56e046
Create Date: 2025-11-03 16:41:52.394363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb2809714bd8'
down_revision: Union[str, None] = 'e9ab0f56e046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'phones')
    op.drop_column('stores', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('phones', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

